import React from "react"
import styled from "@emotion/styled"
import Layout from "../components/Layout"
import {getProfiles,removeProfile,updateProfile} from "../lib/storage"
const Wrap=styled.div`max-width:1200px;margin:0 auto;padding:60px 20px 90px`
const Stats=styled.div`display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0 30px;@media(max-width:720px){grid-template-columns:repeat(2,1fr)}`
const Stat=styled.div`background:#171a22;border:1px solid #242936;border-radius:14px;padding:18px;strong{display:block;font-size:34px}span{color:#8e95a5;font-size:12px;text-transform:uppercase}`
const Table=styled.div`overflow:auto;background:#171a22;border:1px solid #242936;border-radius:14px;table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:14px;border-bottom:1px solid #2a2f3a;text-align:left}th{font-size:11px;text-transform:uppercase;color:#8e95a5}button{margin-right:6px;padding:8px 10px;border:0;border-radius:8px;cursor:pointer}.ok{background:#b6f4dc}.no{background:#f6c66d}.danger{background:#ff657f;color:#fff}`
export default function AdminPage(){const[profiles,setProfiles]=React.useState([]);const refresh=()=>setProfiles(getProfiles());React.useEffect(()=>refresh(),[]);const act=(id,status)=>{updateProfile(id,{status});refresh()};const del=id=>{if(window.confirm("¿Eliminar este perfil?")){removeProfile(id);refresh()}};const pending=profiles.filter(p=>p.status==="pending").length,approved=profiles.filter(p=>p.status==="approved").length,rejected=profiles.filter(p=>p.status==="rejected").length;return <Layout title="Admin | Camellando"><Wrap><p style={{textTransform:"uppercase",letterSpacing:".12em",fontSize:12,color:"#8e95a5"}}>Camellando · Admin</p><h1 style={{fontSize:50,letterSpacing:"-.04em",margin:"0"}}>Gestión del directorio</h1><Stats><Stat><strong>{profiles.length}</strong><span>Total</span></Stat><Stat><strong>{pending}</strong><span>Pendientes</span></Stat><Stat><strong>{approved}</strong><span>Publicados</span></Stat><Stat><strong>{rejected}</strong><span>Rechazados</span></Stat></Stats><Table><table><thead><tr><th>Perfil</th><th>Categoría</th><th>Ciudad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td><strong>{p.businessName||p.displayName}</strong><br/><small>{p.headline}</small></td><td>{p.category}</td><td>{p.city}</td><td>{p.status}</td><td><button className="ok" onClick={()=>act(p.id,"approved")}>Aprobar</button><button className="no" onClick={()=>act(p.id,"rejected")}>Rechazar</button><button onClick={()=>act(p.id,"suspended")}>Suspender</button><button className="danger" onClick={()=>del(p.id)}>Eliminar</button></td></tr>)}</tbody></table></Table></Wrap></Layout>}
