import React from "react"
import styled from "@emotion/styled"
import Layout from "../components/Layout"
import {addProfile} from "../lib/storage"
const Wrap=styled.div`max-width:880px;margin:0 auto;padding:60px 20px 90px`
const Panel=styled.div`background:#171a22;border:1px solid #242936;border-radius:18px;padding:26px`
const Grid=styled.div`display:grid;grid-template-columns:1fr 1fr;gap:14px;@media(max-width:700px){grid-template-columns:1fr}`
const Field=styled.label`display:flex;flex-direction:column;gap:7px;margin-bottom:14px;span{font-size:12px;text-transform:uppercase;letter-spacing:.07em;color:#8e95a5}input,select,textarea{padding:13px 14px;background:#0f1117;color:#fff;border:1px solid #303643;border-radius:10px}textarea{min-height:120px;resize:vertical}`
const Button=styled.button`border:0;border-radius:10px;padding:14px 18px;background:#b6f4dc;color:#111;font-weight:800;cursor:pointer`
const initial={displayName:"",businessName:"",headline:"",description:"",category:"",skills:"",city:"",whatsapp:"",instagram:"",website:"",remoteAvailable:false,onsiteAvailable:true}
export default function PublicarPage(){const[form,setForm]=React.useState(initial);const[sent,setSent]=React.useState(false);const set=(k,v)=>setForm(prev=>({...prev,[k]:v}));const submit=e=>{e.preventDefault();addProfile({...form,skills:form.skills.split(",").map(s=>s.trim()).filter(Boolean)});setForm(initial);setSent(true)};return <Layout title="Publicar | Camellando"><Wrap><p style={{textTransform:"uppercase",letterSpacing:".12em",fontSize:12,color:"#8e95a5"}}>Camellando</p><h1 style={{fontSize:54,letterSpacing:"-.04em",margin:"0 0 8px"}}>¿En qué camellas?</h1><p style={{color:"#aeb4c0",lineHeight:1.6}}>Completa tu perfil. Quedará pendiente hasta que un administrador lo apruebe.</p><Panel>{sent?<div><h2>Perfil enviado</h2><p>Quedó pendiente de revisión.</p><a href="/">Volver al directorio</a></div>:<form onSubmit={submit}><Grid><Field><span>Tu nombre</span><input required value={form.displayName} onChange={e=>set("displayName",e.target.value)}/></Field><Field><span>Marca o negocio</span><input value={form.businessName} onChange={e=>set("businessName",e.target.value)}/></Field><Field><span>Ciudad</span><input required value={form.city} onChange={e=>set("city",e.target.value)}/></Field><Field><span>Categoría</span><select required value={form.category} onChange={e=>set("category",e.target.value)}><option value="">Selecciona</option>{["Diseño","Tecnología","Hogar","Construcción","Arquitectura","Transporte","Eventos","Marketing","Educación","Otros"].map(x=><option key={x}>{x}</option>)}</select></Field><Field><span>WhatsApp</span><input value={form.whatsapp} onChange={e=>set("whatsapp",e.target.value)}/></Field><Field><span>Instagram</span><input value={form.instagram} onChange={e=>set("instagram",e.target.value)}/></Field><Field><span>Sitio web</span><input value={form.website} onChange={e=>set("website",e.target.value)}/></Field><Field><span>Habilidades</span><input required placeholder="Branding, React, Plomería..." value={form.skills} onChange={e=>set("skills",e.target.value)}/></Field></Grid><Field><span>Frase principal</span><input required value={form.headline} onChange={e=>set("headline",e.target.value)}/></Field><Field><span>Descripción</span><textarea required value={form.description} onChange={e=>set("description",e.target.value)}/></Field><div style={{display:"flex",gap:18,flexWrap:"wrap",margin:"8px 0 20px"}}><label><input type="checkbox" checked={form.remoteAvailable} onChange={e=>set("remoteAvailable",e.target.checked)}/> Remoto</label><label><input type="checkbox" checked={form.onsiteAvailable} onChange={e=>set("onsiteAvailable",e.target.checked)}/> Presencial</label></div><Button>Enviar para revisión</Button></form>}</Panel></Wrap></Layout>}
